### ISSUE TITLE
Rebuild containers

### ISSUE THREAD

**Issue by t3chn0m4g3** [dtag-dev-sec/tpotce#89]
- [x] rebuild Conpot include EWS by #88 
- [x] rebuild Cowrie include EWS by #88 
- [x] rebuild Dionaea include EWS by #88 
- [x] rebuild Emobility include EWS by #88 
- [x] rebuild Glastopf (or SNARE / TANNER) include EWS by #88 
- [x] rebuild Honeytrap include EWS by #88  
- [x] rebuild Portainer include latest version / modify auth parameters
